INSTALL
=======
R. S. Doiel <rsdoiel@gmail.com>
Version, 0.0.3x, 2010.04.21

copyright (c) 2010, R. S. Doiel, all rights reserved

Licensed under "The BSD License" described at http://opensource.org/licenses/bsd-license.php

== OVERVIEW

link:README.asciidoc[nshtools] is a NodeJS module. 

== REQUIREMENTS

* node >= 1.91 footnote:[see link:http://nodejs.org[nodejs.org] for details.]
* git footnote:[see link:http://git-scm.com/[git-scm.com] for details]

== INSTALLING

nshtools comes with a simple installer. This is a simple installer written using nshtools to install nshtools module. It has one option.

--Prefix::
        The prefix of where you want things installed.

nshtools needs to have node already installed. See link:http://nodejs.org[http://nodejs.org] for details. 

.simple install
----
node install-nshtools.js
----

.install in /usr/local
----
node install-nshtools.js --prefix=/usr/local
----

== GORY DETAILS

Typically node modules live in two place /usr/local/lib/node/libraries or $HOME/.node_libraries. If you write your own module or download someone elses and don't want to play with `require.paths` you wind up coping that module to where the rest of the modules live.  Likewise if you've written an application you wind up copying it to a "bin" folder on many Unix systems. install-nshtools.js does this for you based on the prefix path provided.

The default prefix path is your local home directory. The installer will fail if the target directories don't exists. That was one of the ways the installer was kept simple.


